# Generated by Django 5.0.2 on 2024-02-13 06:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_date_vendor_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to=core.models.user_directory_path),
            preserve_default=False,
        ),
    ]
