# Generated by Django 5.0.2 on 2024-02-13 07:51

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_vendor_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=15, prefix='', unique=True),
        ),
    ]
